# ==============================================================================
# Config.yml
# ------------------------------------------------------------------------------
#
# This is the main configuration file for the website. The 'theme' value should
# match the name of the folder in /themes that contains your theme files; if
# you've copied the default theme and given it a different name make sure to
# update the value here too.

baseURL: ""

title: "Colloque ECRiDiL 2018"
languageCode: "fr"
defaultContentLanguage: "fr"
theme: "theme-ecridil-2018"
publishDir: site

footnoteReturnLinkContents: "↩"
metaDataFormat: "yaml"
googleAnalytics: ""

pluralizeListTitles: true
disableKinds:
  - "home"
  - "section"
  - "taxonomy"
  - "taxonomyTerm"

markup:
  defaultMarkdownHandler: blackfriday
  blackfriday:
    fractions: false
    hrefTargetBlank: true
    smartypantsQuotesNBSP: true
    smartyPants: true

# These values can be accessed in templates via .Site.Params
params:
  searchEnabled: true
  licenseIcons: true
  citationPageLocationDivider: ", "
  figureLabels: false
  figureLabelsTextBefore: "Figure "
  figureLabelsTextAfter: ". "
  videoFigureFallbackText: true
  videoFigureFallbackTextBefore: "Regardez la vidéo à l’adresse "
  videoFigureFallbackTextAfter: ". "
  websiteFigureFallbackText: true
  websiteFigureFallbackTextBefore: "Visitez site à l’adresse "
  websiteFigureFallbackTextAfter: ". "
  displayBiblioShort: true
  imageDir: ""
  tocType: full
  menuType: short
  objectLinkText: "Voir dans la colletion"
  frontmatterPageStart: 0
  bodyPageStart: 100
  backmatterPageStart: 1000
  citationStyle: apa
  prevPageButtonText: Page précédente
  nextPageButtonText: Page suivante
